=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::CategoriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CategoriesApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::CategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoriesApi' do
    it 'should create an instance of CategoriesApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::CategoriesApi)
    end
  end

  # unit tests for categories_list
  # list categories
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description Only return categories with the given description
  # @option opts [String] :id Only return categories with the given id
  # @option opts [Integer] :limit Maximum number of categories to return
  # @option opts [String] :name Only return categories with the given name
  # @option opts [Integer] :offset The first zero-based offset category to return
  # @option opts [Array<String>] :sort Sort the categories by the given key(s)
  # @return [Categories]
  describe 'categories_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
