=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::CountriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CountriesApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::CountriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CountriesApi' do
    it 'should create an instance of CountriesApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::CountriesApi)
    end
  end

  # unit tests for countries_list
  # list countries
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country_name Only return countries with the given name
  # @option opts [String] :id Only return countries with the given id
  # @option opts [String] :iso_code Only return countries with the given ISO code
  # @option opts [Integer] :limit Maximum number of countries to return
  # @option opts [Integer] :offset The first zero-based offset country to return
  # @option opts [Array<String>] :sort Sort the countries by the given key(s)
  # @return [Countries]
  describe 'countries_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
