=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::FeasibilityApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FeasibilityApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::FeasibilityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeasibilityApi' do
    it 'should create an instance of FeasibilityApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::FeasibilityApi)
    end
  end

  # unit tests for feasibility_show
  # show feasibility
  # @param ext_project_id 
  # @param [Hash] opts the optional parameters
  # @return [Feasibility]
  describe 'feasibility_show test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
