=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::LineItemsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LineItemsApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::LineItemsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LineItemsApi' do
    it 'should create an instance of LineItemsApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::LineItemsApi)
    end
  end

  # unit tests for line_items_close
  # close lineItems
  # @param ext_line_item_id 
  # @param ext_project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreateLineItem]
  describe 'line_items_close test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for line_items_create
  # create lineItems
  # @param ext_project_id 
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [CreateLineItem]
  describe 'line_items_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for line_items_get
  # get lineItems
  # @param ext_line_item_id 
  # @param ext_project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreateLineItem]
  describe 'line_items_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for line_items_get_detailed_line_item_report
  # getDetailedLineItemReport lineItems
  # @param ext_line_item_id 
  # @param ext_project_id 
  # @param [Hash] opts the optional parameters
  # @return [DetailedLineItemReport]
  describe 'line_items_get_detailed_line_item_report test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for line_items_launch
  # launch lineItems
  # @param ext_line_item_id 
  # @param ext_project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreateLineItem]
  describe 'line_items_launch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for line_items_list_line_items
  # listLineItems lineItems
  # @param ext_project_id External Project ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country_iso_code Only return line items with the given country ISO Code
  # @option opts [String] :ext_line_item_id Only return line items with the given extLineItemId
  # @option opts [String] :language_iso_code Only return line items with the given language ISO Code
  # @option opts [Integer] :limit Maximum number of line items to return
  # @option opts [Integer] :offset The first zero-based offset line item to return
  # @option opts [String] :qa_state Only return lineitems with the given QA state
  # @option opts [Array<String>] :sort Sort the line items by the given key(s)
  # @option opts [String] :state Only return lineitems with the given state
  # @option opts [String] :state_reason Only return line items with the given state reason
  # @option opts [String] :title Only return line items with the given title
  # @return [LineItems]
  describe 'line_items_list_line_items test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for line_items_pause
  # pause lineItems
  # @param ext_line_item_id 
  # @param ext_project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreateLineItem]
  describe 'line_items_pause test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for line_items_update
  # update lineItems
  # @param ext_line_item_id 
  # @param ext_project_id 
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [CreateLineItem]
  describe 'line_items_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
