=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::RespondentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RespondentApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::RespondentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RespondentApi' do
    it 'should create an instance of RespondentApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::RespondentApi)
    end
  end

  # unit tests for respondent_entry
  # entry respondent
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'respondent_entry test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for respondent_exit
  # exit respondent
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'respondent_exit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
