=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::SampleSourcesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SampleSourcesApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::SampleSourcesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SampleSourcesApi' do
    it 'should create an instance of SampleSourcesApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::SampleSourcesApi)
    end
  end

  # unit tests for sample_sources_list
  # list sampleSources
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id Only return sources with the given id
  # @option opts [Integer] :limit Maximum number of sources to return
  # @option opts [String] :name Only return sources with the given name
  # @option opts [Integer] :offset The first zero-based offset source to return
  # @option opts [Array<String>] :sort Sort the sources by the given key(s)
  # @option opts [String] :source Only return source with the given source
  # @option opts [String] :survey_topic Only return sources with the given surveyTopic
  # @return [SampleSources]
  describe 'sample_sources_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
