=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::StudyMetadataApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StudyMetadataApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::StudyMetadataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StudyMetadataApi' do
    it 'should create an instance of StudyMetadataApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::StudyMetadataApi)
    end
  end

  # unit tests for study_metadata_list
  # list studyMetadata
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description Only return categories with the given description
  # @option opts [String] :id Only return categories with the given id
  # @option opts [Integer] :limit Maximum number of studyMetadata to return
  # @option opts [String] :name Only return categories with the given name
  # @option opts [Integer] :offset The first zero-based offset studyMetadata to return
  # @option opts [Array<String>] :sort Sort the studyMetadata by the given key(s)
  # @return [StudyMetadata]
  describe 'study_metadata_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
