=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SamplifyAPIClient::UsersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::UsersApi)
    end
  end

  # unit tests for users_get_user_info
  # getUserInfo users
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :app_id Only return apps with the given id
  # @option opts [BOOLEAN] :current Only return current app for the user id
  # @option opts [BOOLEAN] :default Only return default app for the user id
  # @option opts [String] :name Only return apps with the given name
  # @return [UserInfo]
  describe 'users_get_user_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
