=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SamplifyAPIClient::QuotaCellFeasibility
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'QuotaCellFeasibility' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::QuotaCellFeasibility.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QuotaCellFeasibility' do
    it 'should create an instance of QuotaCellFeasibility' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::QuotaCellFeasibility)
    end
  end
  describe 'test attribute "feasibility_count"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "quota_cell_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "quota_nodes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
