=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SamplifyAPIClient::ReconcileData
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReconcileData' do
  before do
    # run before each test
    @instance = SamplifyAPIClient::ReconcileData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReconcileData' do
    it 'should create an instance of ReconcileData' do
      expect(@instance).to be_instance_of(SamplifyAPIClient::ReconcileData)
    end
  end
end
