=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

# Common files
require 'samplify_api_client/api_client'
require 'samplify_api_client/api_error'
require 'samplify_api_client/version'
require 'samplify_api_client/configuration'

# Models
require 'samplify_api_client/models/app_error'
require 'samplify_api_client/models/application_item_data'
require 'samplify_api_client/models/attr_category'
require 'samplify_api_client/models/attribute_category'
require 'samplify_api_client/models/attribute_data'
require 'samplify_api_client/models/attribute_option'
require 'samplify_api_client/models/attributes'
require 'samplify_api_client/models/auth_error'
require 'samplify_api_client/models/author'
require 'samplify_api_client/models/buy_project'
require 'samplify_api_client/models/buy_project_item'
require 'samplify_api_client/models/buy_project_response'
require 'samplify_api_client/models/buy_projects_payload'
require 'samplify_api_client/models/categories'
require 'samplify_api_client/models/category_data'
require 'samplify_api_client/models/code_payload'
require 'samplify_api_client/models/countries'
require 'samplify_api_client/models/country_data'
require 'samplify_api_client/models/create_line_item'
require 'samplify_api_client/models/create_project'
require 'samplify_api_client/models/create_project_data'
require 'samplify_api_client/models/create_project_payload'
require 'samplify_api_client/models/detailed_quote'
require 'samplify_api_client/models/end_links'
require 'samplify_api_client/models/error_type'
require 'samplify_api_client/models/errors'
require 'samplify_api_client/models/event'
require 'samplify_api_client/models/event_data'
require 'samplify_api_client/models/event_list_data'
require 'samplify_api_client/models/events'
require 'samplify_api_client/models/exclusion_data'
require 'samplify_api_client/models/feasibility'
require 'samplify_api_client/models/feasibility_data'
require 'samplify_api_client/models/feasibility_response_data'
require 'samplify_api_client/models/line_item_action_response'
require 'samplify_api_client/models/line_item_data'
require 'samplify_api_client/models/line_item_item_data'
require 'samplify_api_client/models/line_item_report_data'
require 'samplify_api_client/models/line_item_response_data'
require 'samplify_api_client/models/line_item_source'
require 'samplify_api_client/models/line_items'
require 'samplify_api_client/models/links'
require 'samplify_api_client/models/logout_payload'
require 'samplify_api_client/models/meta'
require 'samplify_api_client/models/order_detail'
require 'samplify_api_client/models/order_detail_response_data'
require 'samplify_api_client/models/project'
require 'samplify_api_client/models/project_action'
require 'samplify_api_client/models/project_action_response'
require 'samplify_api_client/models/project_category_data'
require 'samplify_api_client/models/project_item_data'
require 'samplify_api_client/models/project_report'
require 'samplify_api_client/models/project_report_data'
require 'samplify_api_client/models/project_reports'
require 'samplify_api_client/models/project_response'
require 'samplify_api_client/models/project_response_data'
require 'samplify_api_client/models/project_survey_end_links'
require 'samplify_api_client/models/project_survey_end_links_data'
require 'samplify_api_client/models/projects'
require 'samplify_api_client/models/quota_cell'
require 'samplify_api_client/models/quota_cell_feasibility'
require 'samplify_api_client/models/quota_group_dat'
require 'samplify_api_client/models/quota_group_data'
require 'samplify_api_client/models/quota_group_feasibility'
require 'samplify_api_client/models/quota_plan_data'
require 'samplify_api_client/models/quote'
require 'samplify_api_client/models/reconcile'
require 'samplify_api_client/models/reconcile_data'
require 'samplify_api_client/models/refresh_token_payload'
require 'samplify_api_client/models/reprice'
require 'samplify_api_client/models/reprice_data'
require 'samplify_api_client/models/reprice_payload'
require 'samplify_api_client/models/resource'
require 'samplify_api_client/models/respondent_filter_data'
require 'samplify_api_client/models/sales_order'
require 'samplify_api_client/models/sales_order_details'
require 'samplify_api_client/models/sample_source'
require 'samplify_api_client/models/sample_source_category'
require 'samplify_api_client/models/sample_source_data'
require 'samplify_api_client/models/sample_sources'
require 'samplify_api_client/models/state_change'
require 'samplify_api_client/models/state_change_data'
require 'samplify_api_client/models/state_change_payload'
require 'samplify_api_client/models/status'
require 'samplify_api_client/models/supported_language'
require 'samplify_api_client/models/survey_end_links'
require 'samplify_api_client/models/survey_test'
require 'samplify_api_client/models/survey_test_id'
require 'samplify_api_client/models/survey_test_link'
require 'samplify_api_client/models/target'
require 'samplify_api_client/models/targeting_attribute'
require 'samplify_api_client/models/token_media'
require 'samplify_api_client/models/token_payload'
require 'samplify_api_client/models/url_param'
require 'samplify_api_client/models/update_line_item'
require 'samplify_api_client/models/update_project_data'
require 'samplify_api_client/models/update_project_line_item'
require 'samplify_api_client/models/user_info'
require 'samplify_api_client/models/user_info_response_data'

# APIs
require 'samplify_api_client/api/attributes_api'
require 'samplify_api_client/api/auth_api'
require 'samplify_api_client/api/categories_api'
require 'samplify_api_client/api/countries_api'
require 'samplify_api_client/api/default_api'
require 'samplify_api_client/api/events_api'
require 'samplify_api_client/api/feasibility_api'
require 'samplify_api_client/api/line_items_api'
require 'samplify_api_client/api/order_details_api'
require 'samplify_api_client/api/projects_api'
require 'samplify_api_client/api/respondent_api'
require 'samplify_api_client/api/sample_sources_api'
require 'samplify_api_client/api/users_api'

module SamplifyAPIClient
  class << self
    # Customize default settings for the SDK using block.
    #   SamplifyAPIClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
