=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'date'

module SamplifyAPIClient
  class QuotaGroupDat
    # line item ID
    attr_accessor :line_item_id

    # Picker event ID
    attr_accessor :picker_event_id

    # ID
    attr_accessor :quota_group_id

    # sales order ID
    attr_accessor :sales_order_detail_id

    # survey ID
    attr_accessor :survey_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'line_item_id' => :'lineItemId',
        :'picker_event_id' => :'pickerEventId',
        :'quota_group_id' => :'quotaGroupId',
        :'sales_order_detail_id' => :'salesOrderDetailId',
        :'survey_id' => :'surveyId'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'line_item_id' => :'String',
        :'picker_event_id' => :'Integer',
        :'quota_group_id' => :'Integer',
        :'sales_order_detail_id' => :'String',
        :'survey_id' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'lineItemId')
        self.line_item_id = attributes[:'lineItemId']
      end

      if attributes.has_key?(:'pickerEventId')
        self.picker_event_id = attributes[:'pickerEventId']
      end

      if attributes.has_key?(:'quotaGroupId')
        self.quota_group_id = attributes[:'quotaGroupId']
      end

      if attributes.has_key?(:'salesOrderDetailId')
        self.sales_order_detail_id = attributes[:'salesOrderDetailId']
      end

      if attributes.has_key?(:'surveyId')
        self.survey_id = attributes[:'surveyId']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @line_item_id.nil?
        invalid_properties.push('invalid value for "line_item_id", line_item_id cannot be nil.')
      end

      if @picker_event_id.nil?
        invalid_properties.push('invalid value for "picker_event_id", picker_event_id cannot be nil.')
      end

      if @quota_group_id.nil?
        invalid_properties.push('invalid value for "quota_group_id", quota_group_id cannot be nil.')
      end

      if @sales_order_detail_id.nil?
        invalid_properties.push('invalid value for "sales_order_detail_id", sales_order_detail_id cannot be nil.')
      end

      if @survey_id.nil?
        invalid_properties.push('invalid value for "survey_id", survey_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @line_item_id.nil?
      return false if @picker_event_id.nil?
      return false if @quota_group_id.nil?
      return false if @sales_order_detail_id.nil?
      return false if @survey_id.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          line_item_id == o.line_item_id &&
          picker_event_id == o.picker_event_id &&
          quota_group_id == o.quota_group_id &&
          sales_order_detail_id == o.sales_order_detail_id &&
          survey_id == o.survey_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [line_item_id, picker_event_id, quota_group_id, sales_order_detail_id, survey_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SamplifyAPIClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
