=begin
#Samplify API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'date'

module SamplifyAPIClient
  class SurveyTest
    # indicates the status of the test
    attr_accessor :disposition

    # if the test wasnt successful, this indicates the reason behind failure
    attr_accessor :fail_reason

    # denotes if the test was successful or not
    attr_accessor :is_successful

    # Respondent  id that was used for this test
    attr_accessor :pid

    # unique session id that was used for this test
    attr_accessor :psid

    # timestamp of when the test was completed
    attr_accessor :tested_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'disposition' => :'disposition',
        :'fail_reason' => :'failReason',
        :'is_successful' => :'isSuccessful',
        :'pid' => :'pid',
        :'psid' => :'psid',
        :'tested_at' => :'testedAt'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'disposition' => :'String',
        :'fail_reason' => :'String',
        :'is_successful' => :'BOOLEAN',
        :'pid' => :'String',
        :'psid' => :'String',
        :'tested_at' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'disposition')
        self.disposition = attributes[:'disposition']
      end

      if attributes.has_key?(:'failReason')
        self.fail_reason = attributes[:'failReason']
      end

      if attributes.has_key?(:'isSuccessful')
        self.is_successful = attributes[:'isSuccessful']
      end

      if attributes.has_key?(:'pid')
        self.pid = attributes[:'pid']
      end

      if attributes.has_key?(:'psid')
        self.psid = attributes[:'psid']
      end

      if attributes.has_key?(:'testedAt')
        self.tested_at = attributes[:'testedAt']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @disposition.nil?
        invalid_properties.push('invalid value for "disposition", disposition cannot be nil.')
      end

      if @is_successful.nil?
        invalid_properties.push('invalid value for "is_successful", is_successful cannot be nil.')
      end

      if @pid.nil?
        invalid_properties.push('invalid value for "pid", pid cannot be nil.')
      end

      if @psid.nil?
        invalid_properties.push('invalid value for "psid", psid cannot be nil.')
      end

      if @tested_at.nil?
        invalid_properties.push('invalid value for "tested_at", tested_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @disposition.nil?
      return false if @is_successful.nil?
      return false if @pid.nil?
      return false if @psid.nil?
      return false if @tested_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          disposition == o.disposition &&
          fail_reason == o.fail_reason &&
          is_successful == o.is_successful &&
          pid == o.pid &&
          psid == o.psid &&
          tested_at == o.tested_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [disposition, fail_reason, is_successful, pid, psid, tested_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SamplifyAPIClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
